package backend;

/**
 *
 * @author Elwin Slokker
 */
public enum LuggageEnum {
    TRUNK, BAG, SUITCASE, SACK, KNAPSACK, CASE, TOTEBAG, DUFFEL, SATCHEL, SADDLEBAG, POUCH, BRIEFCASE, PURSE, HANDBAG, RUCKSACK, BAGGAGE, SHOPPINGBAG
}